# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'armadillo.ui'
#
# Created: Sat Feb  8 16:07:33 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(641, 497)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("img/armadillo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.fr_toolbar = QtGui.QFrame(self.centralwidget)
        self.fr_toolbar.setFrameShape(QtGui.QFrame.NoFrame)
        self.fr_toolbar.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_toolbar.setObjectName(_fromUtf8("fr_toolbar"))
        self.gridLayout_2 = QtGui.QGridLayout(self.fr_toolbar)
        self.gridLayout_2.setContentsMargins(2, 0, 2, 0)
        self.gridLayout_2.setHorizontalSpacing(2)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.b_save = QtGui.QToolButton(self.fr_toolbar)
        self.b_save.setMinimumSize(QtCore.QSize(26, 0))
        self.b_save.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("img/save.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_save.setIcon(icon1)
        self.b_save.setObjectName(_fromUtf8("b_save"))
        self.gridLayout_2.addWidget(self.b_save, 0, 4, 1, 1)
        self.b_wordwrap = QtGui.QToolButton(self.fr_toolbar)
        self.b_wordwrap.setMinimumSize(QtCore.QSize(26, 0))
        self.b_wordwrap.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("img/wordwrap.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_wordwrap.setIcon(icon2)
        self.b_wordwrap.setObjectName(_fromUtf8("b_wordwrap"))
        self.gridLayout_2.addWidget(self.b_wordwrap, 0, 10, 1, 1)
        self.b_open = QtGui.QToolButton(self.fr_toolbar)
        self.b_open.setMinimumSize(QtCore.QSize(26, 0))
        self.b_open.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("img/file_open.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_open.setIcon(icon3)
        self.b_open.setObjectName(_fromUtf8("b_open"))
        self.gridLayout_2.addWidget(self.b_open, 0, 3, 1, 1)
        self.b_workspace = QtGui.QPushButton(self.fr_toolbar)
        self.b_workspace.setMinimumSize(QtCore.QSize(26, 0))
        self.b_workspace.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("img/workspace.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_workspace.setIcon(icon4)
        self.b_workspace.setObjectName(_fromUtf8("b_workspace"))
        self.gridLayout_2.addWidget(self.b_workspace, 0, 1, 1, 1)
        self.frame = QtGui.QFrame(self.fr_toolbar)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setHorizontalSpacing(2)
        self.gridLayout_3.setVerticalSpacing(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.b_help = QtGui.QToolButton(self.frame)
        self.b_help.setMinimumSize(QtCore.QSize(26, 0))
        self.b_help.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("img/home.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_help.setIcon(icon5)
        self.b_help.setObjectName(_fromUtf8("b_help"))
        self.gridLayout_3.addWidget(self.b_help, 0, 3, 1, 1)
        spacerItem = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 2, 1, 1)
        self.fr_find = QtGui.QFrame(self.frame)
        self.fr_find.setMinimumSize(QtCore.QSize(150, 0))
        self.fr_find.setMaximumSize(QtCore.QSize(250, 16777215))
        self.fr_find.setStyleSheet(_fromUtf8("border:0px;"))
        self.fr_find.setFrameShape(QtGui.QFrame.NoFrame)
        self.fr_find.setFrameShadow(QtGui.QFrame.Raised)
        self.fr_find.setObjectName(_fromUtf8("fr_find"))
        self.gridLayout_4 = QtGui.QGridLayout(self.fr_find)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.le_find = QtGui.QLineEdit(self.fr_find)
        self.le_find.setMinimumSize(QtCore.QSize(150, 0))
        self.le_find.setObjectName(_fromUtf8("le_find"))
        self.gridLayout_4.addWidget(self.le_find, 0, 3, 1, 1)
        self.b_find = QtGui.QPushButton(self.fr_find)
        self.b_find.setMaximumSize(QtCore.QSize(16777215, 25))
        self.b_find.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("img/search.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_find.setIcon(icon6)
        self.b_find.setObjectName(_fromUtf8("b_find"))
        self.gridLayout_4.addWidget(self.b_find, 0, 4, 1, 1)
        self.le_goto = QtGui.QLineEdit(self.fr_find)
        self.le_goto.setMinimumSize(QtCore.QSize(40, 0))
        self.le_goto.setMaximumSize(QtCore.QSize(50, 16777215))
        self.le_goto.setObjectName(_fromUtf8("le_goto"))
        self.gridLayout_4.addWidget(self.le_goto, 0, 1, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 0, 2, 1, 1)
        self.gridLayout_3.addWidget(self.fr_find, 0, 12, 1, 1)
        self.b_run = QtGui.QToolButton(self.frame)
        self.b_run.setMinimumSize(QtCore.QSize(26, 0))
        self.b_run.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("img/tri_right.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_run.setIcon(icon7)
        self.b_run.setObjectName(_fromUtf8("b_run"))
        self.gridLayout_3.addWidget(self.b_run, 0, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 0, 9, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 0, 1, 1)
        self.b_settings = QtGui.QToolButton(self.frame)
        self.b_settings.setMinimumSize(QtCore.QSize(26, 0))
        self.b_settings.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("img/wrench.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_settings.setIcon(icon8)
        self.b_settings.setObjectName(_fromUtf8("b_settings"))
        self.gridLayout_3.addWidget(self.b_settings, 0, 5, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 7, 1, 1)
        self.b_plugins = QtGui.QToolButton(self.frame)
        self.b_plugins.setMinimumSize(QtCore.QSize(26, 0))
        self.b_plugins.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("img/plugin.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_plugins.setIcon(icon9)
        self.b_plugins.setObjectName(_fromUtf8("b_plugins"))
        self.gridLayout_3.addWidget(self.b_plugins, 0, 4, 1, 1)
        self.b_main = QtGui.QPushButton(self.frame)
        self.b_main.setMinimumSize(QtCore.QSize(24, 24))
        self.b_main.setText(_fromUtf8(""))
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8("img/menu.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_main.setIcon(icon10)
        self.b_main.setObjectName(_fromUtf8("b_main"))
        self.gridLayout_3.addWidget(self.b_main, 0, 8, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 11, 1, 1)
        self.b_unindent = QtGui.QToolButton(self.fr_toolbar)
        self.b_unindent.setMinimumSize(QtCore.QSize(26, 0))
        self.b_unindent.setText(_fromUtf8(""))
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8("img/indent_remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_unindent.setIcon(icon11)
        self.b_unindent.setObjectName(_fromUtf8("b_unindent"))
        self.gridLayout_2.addWidget(self.b_unindent, 0, 7, 1, 1)
        self.b_indent = QtGui.QToolButton(self.fr_toolbar)
        self.b_indent.setMinimumSize(QtCore.QSize(26, 0))
        self.b_indent.setText(_fromUtf8(""))
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8("img/indent.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_indent.setIcon(icon12)
        self.b_indent.setObjectName(_fromUtf8("b_indent"))
        self.gridLayout_2.addWidget(self.b_indent, 0, 6, 1, 1)
        self.b_comment = QtGui.QToolButton(self.fr_toolbar)
        self.b_comment.setMinimumSize(QtCore.QSize(26, 0))
        self.b_comment.setText(_fromUtf8(""))
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8("img/comment.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_comment.setIcon(icon13)
        self.b_comment.setObjectName(_fromUtf8("b_comment"))
        self.gridLayout_2.addWidget(self.b_comment, 0, 8, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem5, 0, 9, 1, 1)
        self.b_new = QtGui.QPushButton(self.fr_toolbar)
        self.b_new.setMinimumSize(QtCore.QSize(26, 0))
        self.b_new.setText(_fromUtf8(""))
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8("img/new.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.b_new.setIcon(icon14)
        self.b_new.setObjectName(_fromUtf8("b_new"))
        self.gridLayout_2.addWidget(self.b_new, 0, 0, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(10, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem6, 0, 5, 1, 1)
        self.gridLayout.addWidget(self.fr_toolbar, 0, 0, 1, 1)
        self.sw_main = QtGui.QStackedWidget(self.centralwidget)
        self.sw_main.setObjectName(_fromUtf8("sw_main"))
        self.gridLayout.addWidget(self.sw_main, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QObject.connect(self.le_find, QtCore.SIGNAL(_fromUtf8("returnPressed()")), self.b_find.click)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Armadillo", None))
        self.b_save.setToolTip(_translate("MainWindow", "Save", None))
        self.b_wordwrap.setToolTip(_translate("MainWindow", "Toggle Wordwrap", None))
        self.b_open.setToolTip(_translate("MainWindow", "Open", None))
        self.b_workspace.setToolTip(_translate("MainWindow", "Workspaces", None))
        self.b_help.setToolTip(_translate("MainWindow", "afide Help", None))
        self.le_find.setPlaceholderText(_translate("MainWindow", "Find", None))
        self.le_goto.setPlaceholderText(_translate("MainWindow", "goto", None))
        self.b_run.setToolTip(_translate("MainWindow", "Run", None))
        self.b_settings.setToolTip(_translate("MainWindow", "Edit Settings", None))
        self.b_plugins.setToolTip(_translate("MainWindow", "Show/Hide Plugins and Toolbars", None))
        self.b_main.setToolTip(_translate("MainWindow", "Armidillo Menu", None))
        self.b_unindent.setToolTip(_translate("MainWindow", "Unindent", None))
        self.b_indent.setToolTip(_translate("MainWindow", "Indent", None))
        self.b_comment.setToolTip(_translate("MainWindow", "Comment/Uncomment", None))
        self.b_new.setToolTip(_translate("MainWindow", "New", None))

