lang:
    Python:
        plugins: [
                    pycute,
                    qt2py,
                    outline,
                ]
        editor: scintilla
        run: python
##        run: subprocess.Popen(['python', '$file',], stdout=subprocess.PIPE, stdin=subprocess.PIPE, stderr=subprocess.STDOUT, shell=0)
##        run: subprocess.Popen(['python', '$file',], shell=0)
    HTML:
        editor: scintilla
        plugins: [
                    outline,
                ]
        run: webbrowser
    JavaScript:
        editor: scintilla
        plugins: [
                    outline,
                ]
    YAML:
        editor: scintilla
        plugins: [
                    filebrowser
                ]
    CSS:
        editor: scintilla
        plugins: [
                    filebrowser,
                    outline,
                ]
    HTML WYSIWYG:
        editor: ckeditor
        plugins: [
                ]
        run: webbrowser
    WebView:
        editor: webview
        plugins: []
    Text:
        editor: scintilla
        plugins: [
                    filebrowser,
                ]
    SQL:
        editor: scintilla
        plugins: [
                    filebrowser,
                ]
    Bash:
        editor: scintilla
        plugins: [
                ]
    UI:
        editor: scintilla
        plugins: []
        
# Loaded plugins
plugins: 
    outline: 
        dockarea: left
        title: Outline
    filebrowser: 
        dockarea: left
        title: File Browser
    pycute:
        dockarea: bottom
        title: Python Shell
    qt2py:
       dockarea: bottom
       title: PyQt Converter
    find_replace:
        dockarea: bottom
        title: Find / Replace
    output:
        dockarea: bottom
        title: Output
    # py_shell:
        # dockarea: bottom
        
# Plugins always visible
plugins_view: [
    filebrowser, 
    find_replace,
    ]

view_folder: 0
    
# File Extension to Language
ext:
    py: Python
    js: JavaScript
    html: HTML
    css: CSS
    style: CSS
    yml: YAML
    ui: XML
    xml: XML
    sh: Bash
    sql: SQL
    txt: Text
    
