lang:
    Python:
        plugins: [
                    pycute,
                    outline,
                    filebrowser,
                ]
        editor: scintilla
        run: subprocess.Popen(['python', '$file'], stdout=subprocess.PIPE, shell=0)
    HTML:
        editor: scintilla
        plugins: [
                    filebrowser
                ]
        run: webbrowser.open('$file')
    JavaScript:
        editor: scintilla
        plugins: [
                    filebrowser
                ]
    YAML:
        editor: scintilla
        plugins: [
                    filebrowser
                ]
    CSS:
        editor: scintilla
        plugins: [
                    filebrowser,
                    outline
                ]
    HTML WYSIWYG:
        editor: ckeditor
        plugins: [
                ]
        run: webbrowser.open('$file')
    WebView:
        editor: webview
        plugins: []
    Text:
        editor: scintilla
        plugins: [
                    filebrowser,
                ]
plugins: 
    outline: 
        dockarea: left
    filebrowser: 
        dockarea: left
    pycute:
        dockarea: bottom
    # py_shell:
        # dockarea: bottom
ext:
    py: Python
    js: JavaScript
    html: HTML
    htm: HTML
    css: CSS
    style: CSS
    yaml: YAML
    ui: XML
    xml: XML
    
