lang:
    Python:
        plugins: [
                    pycute,
                    outline,
                    filebrowser,
                    qt2py,
                    find_replace,
                ]
        editor: scintilla
        run: subprocess.Popen(['python', '$file'], stdout=subprocess.PIPE, shell=0)
    HTML:
        editor: scintilla
        plugins: [
                    filebrowser,
                    find_replace,
                ]
        run: webbrowser.open('$file')
    JavaScript:
        editor: scintilla
        plugins: [
                    filebrowser
                ]
    YAML:
        editor: scintilla
        plugins: [
                    filebrowser
                ]
    CSS:
        editor: scintilla
        plugins: [
                    filebrowser,
                    outline
                ]
    HTML WYSIWYG:
        editor: ckeditor
        plugins: [
                ]
        run: webbrowser.open('$file')
    WebView:
        editor: webview
        plugins: []
    Text:
        editor: scintilla
        plugins: [
                    filebrowser,
                ]
    SQL:
        editor: scintilla
        plugins: [
                    filebrowser,
                ]
    Bash:
        editor: scintilla
        plugins: [
                ]
    UI:
        editor: scintilla
        plugins: []
plugins: 
    outline: 
        dockarea: left
        title: Outline
    filebrowser: 
        dockarea: left
        title: File Browser
    pycute:
        dockarea: bottom
        title: Python Shell
    qt2py:
       dockarea: bottom
       title: PyQt Converter
    find_replace:
        dockarea: bottom
        title: Find / Replace
    # py_shell:
        # dockarea: bottom
ext:
    py: Python
    js: JavaScript
    html: HTML
    htm: HTML
    css: CSS
    style: CSS
    yaml: YAML
    ui: XML
    xml: XML
    sh: Bash
    sql: SQL
    
